# Generated by Django 3.2.13 on 2023-01-01 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=200)),
                ('imoge', models.CharField(max_length=10)),
                ('is_update', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('theme_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theme_likes', models.ManyToManyField(related_name='user_themes_likes', to=settings.AUTH_USER_MODEL)),
                ('theme_tags', models.ManyToManyField(related_name='tag_themes', to='themes.Tag')),
            ],
        ),
    ]
